#+TITLE: FCNTS organization file

* title and abstract instructions:
https://researchseminars.org/seminar/FCNTS

Go to Edit Schedule, then details, and there is a link you can send to the speaker

I'm trying out something new, which is to use ResearchSeminars.org for the seminar. One merit to this is that I can send speakers a link and have them upload their title and abstract at their leisure. Here's the links

https://researchseminars.org/edit/talk/FCNTS/7/e395bfad56ac7277

and let me know if you have any problems with the link.

* organization and speakers

(Speaking) Michael Allen (VAP, Wesleyan) https://michaelgallen.com/, Folsom suggested
(Speaking) Nicole Looper (just moved from UIC to Brown) 
(Speaking) Jen Paulhus (just moved to Mt. Holyoke last year)
(Speaking) Kate Finnerty
(Speaking) Louis Gaudet
(Speaking) Robin Zhang (MIT https://math.mit.edu/~robinz/)
(Speaking) Rylen G-L (union)

Brody Lynch (UMASS student)
Seong Eun Jung (UMASS student)
Jeff Hatley (Union)

Ben hoirk
Sina Saleh, a current grad student at Harvard (under Laura DeMarco). I think he's got a year or two more, so it might make more sense to wait until next year, but just FYI.
Asimina Hamakiotes (Fordham https://asiminah.github.io/, just moved)
Mike Cerchia (DZB student, postdoc in Maine)
Drew Sutherland (MIT https://math.mit.edu/~drew/)
Rebecca Bellovin (UCONN, her first year as faculty)
Frank Thorne
Lance Edward Miller (Arkansas)
Jeremy Booher (Floridia)

(Spring; DZB would like to be here) Zach Porat (Wesylean)
(Spring?) Alice Lin 
(Spring) Juanita 
(Probably Spring)Trevor Hyde (Vassar, AC alum https://www.vassar.edu/faculty/thyde)
(Spring) Aaron Landesman (Harvard https://people.math.harvard.edu/~landesman/)

(Seems not interested) Joshua Stucky

(Probably have to wait until they're on sabbatical) Scott Ahlgren

I'm on sabbatical and out of town Oct 7, Oct 21, Nov 11, Nov 18, Dec 2; also, Oct 14 is Fall break, and Nov 25 is Thanksgiving break

Here's the schedule so far.

Dates:
Sept 2 - Organizational meeting
Sept 9 
Sept 16
Sept 23
Sept 30
Oct 7 dzb out of town
Oct 14 Fall break 
Oct 21 dzb out of town
Oct 28
Nov 4
Nov 11 dzb out of town
Nov 18 dzb out of town
Nov 25 thanksgiving break
Dec 2 dzb out of town
Dec 9

Spring dates:

Jan 27
Feb 3 
Feb 10
Feb 17 DZB out of town
Feb 24 hopefully Brandon Alberts visits now
Mar 3 DZB out of town probably
Mar 10 DZB out of town
Mar 17 SPRING BREAK
Mar 24 DZB out of town
March 31
Apr 7
Apr 14
Apr 21 APRIL BREAK 
Apr 28 
May 5

Some of the later dates we might need to hold for honors thesis week.


* funding note
Actually, I reread the email thread I sent you, and it says "Faculty seminar funds can be used for light refreshments, co-sponsorships, and expenses for visitors (e.g., travel, food, honoraria). Funds cannot be used to pay for meals for regular seminar members." So that settles the second question.
* reminder email


Five Colleges Number Theory Seminar this Tuesday, September 15, by John Cullinan (4pm in Seeley Mudd 207)


https://faculty.bard.edu/cullinan/

Our seminar continues this week with John Cullinan of Bard College (4pm, in SMUDD 207). 

We plan to head to the dinner after the seminar; let me know if you would like to join us!

Title: Explicit Arithmetic in Isogeny-Torsion Graphs

Abstract: Let E and E’ be isogenous elliptic curves defined over Q. Then their associated L-functions are equal; in particular, their leading Taylor coefficients are equal. However (assuming the conjecture of Birch and Swinnerton-Dyer), the individual arithmetic invariants that comprise the leading terms may not be. In this talk we explore how the individual BSD terms change under a prime-degree isogeny and how to quantify the “likelihood” that such changes occur. This is joint work with Alexander Barrios.

** more
A few reminders: 
 - We have a few seminars scheduled: Sept 24, Claire Frechette (Boston College), but are looking for more speakers.
 - The seminar schedule is at the webpage here https://dmzb.github.io/FCNTS.html


** me

Title: Angle ranks of Abelian varieties

Abstract: I will discuss an elementary notion -- the rank of the multiplicative group generated by roots of a polynomial. For Weil polynomials one calls this the angle rank.  I'll present new results about angle ranks and give some applications to the Tate conjecture for Abelian varieties over finite fields and to arithmetic statistics.

* invitation email

Dear Kate,

It was great meeting you at ICERM! 

I'm writing on behalf of the Pioneer Valley number theory group to invite you
to speak at the Five Colleges Number Theory seminar.

This seminar, which includes Amherst College, Hampshire College, Mt Holyoke
College, Smith College and UMass Amherst, meets Tuesdays at 4pm (usually at
Amherst College). Talks are 50 minutes with 10 minutes for questions. The
audience covers a mix of research areas within number theory and also includes
UMass phd students.

Please let me know if you are interested and available!

The webpage and schedule/list of open dates are here:

https://dmzb.github.io/FCNTS.html

I'm on sabbatical and will be in and out of town; I would prefer to be at your
talk (though this is not strictly necessary!), and among the remaining
available dates, I am in town on Oct 28, Nov 4, Dec 9.

We have a modest budget for the seminar and can pay for meals and
transportation, but not for lodging for local-ish speakers (i.e. from MA or
CT).

The group usually meets for lunch and dinner the day of the seminar, if the
speaker is available.

Let me know if you can speak, in which case I'll send you more information. If
none of these dates work, we can defer the invitation until the following
semester.






* seminar info email for speakers
It is! Talk is at 4pm, 50 minutes, and the room is set up for chalk (no sliding
boards but a lot of board space) or slides.

We usually go to lunch if you're around early enough, and dinner afterwards.
Usually between 8-14 people in the audience, including some UMASS grad
students. My cell number is 510 508 0255, in case anything comes up the day of.

Math dept is Seeley Mudd Building, 31 Quadrangle, Amherst, MA 01002. This is
the southeast corner of the main quad. I’m on 502, and the talk is in 207. I
think you already know this, but the seminar is at Amherst College, not UMASS
Amherst. (We have occasionally had a speaker go to the wrong campus.)

Parking. If you reply with your car's plate #, state of plate, and make and
model, and phone number, I can have a parking permit sent to you to print;
leave it on your dashboard. Try to park on the main quad near Seeley--Mudd.
There is also parking at the Wolff Fitness Center, and (further away) at the
Alumni Lot. If you forget to print the pass, I can print it and bring it to
you.

Looking forward to your visit and talk!
-DZB


We can pay for a rental car. Park on the main quad (there are no parking
decks), and if you text me your rental's plate #, state of plate, and make and
model I can print you a parking permit to give you when you arrive.

No one has used our guest room yet so please do stay!

I finish teaching around 2:15 and am free until 4, so if you show up early we
can get coffee and/or chat. If you can make it for lunch (noon) let me know and
I'll advertise it, but I assume you can't.

If you don't mind, text me your eta once you're on the road.

We're looking forward to seeing you!

* fc organizational email

Five Colleges Number Theory Seminar organizational meeting this Tuesday,
September 2 (4pm in SMudd 207).

Hi everyone,

I'm writing to invite you to an organizational meeting this Tuesday (September
2, 4pm in SMudd 207) for our seminar. (The room is not confirmed yet; if there
is a change I will email everyone Tuesday morning.)


If you can't make it, but there is someone you would like me to invite (or
better, if you would like to volunteer to speak!) please let me know.


A few other things:

(1) I want to welcome Santiago Arango-Piñeros to the area! Santi is my former
student, and is now a postdoc at UMASS. Welcome Santi!

https://sarangop1728.github.io/

(2) We have one speaker scheduled so far: Sept 9, John Cullian (Bard College)

(3) I'm on sabbatical this year and will be in and out of town; Santi will be
the main organizer, but I'll still be helping out (especially with
reimbursements).

(4) If I left anyone off of the organizer list (or if anyone receiving this
email would prefer not to receive organizer emails), and if there is anyone new
to the area to add to the main mailing list, please let me know!


** omitted
(5) I am hosting the webpge here

https://dmzb.github.io/FCNTS.html

I've retired the old Google Calendar and replaced it with ResearchSeminars.org. 

https://researchseminars.org/seminar/FCNTS



which has a calendar of speakers at the bottom. 

* fc mailing list

Robert Benedetto <rlbenedetto@amherst.edu>,
Gregory Call <gscall@amherst.edu>,
Harris Daniels <hdaniels@amherst.edu>,
Amanda Folsom <afolsom@amherst.edu>,
David Zureick-Brown <dzureickbrown@amherst.edu>,
Tom Weston <tweston@umass.edu>,
Siman Wong <siman@umass.edu>,
Paul Gunnells <gunnells@umass.edu>,
Farshid Hajir <hajir@umass.edu>,
Santiago Arango-Piñeros <santiago.arango.pineros@gmail.com>,
Jen Paulhus <jpaulhus@mtholyoke.edu>,
Tori Day <tori.day@mtholyoke.edu>,
Louis Gaudet <lgaudet@umass.edu>,
David Cox <dacox@amherst.edu>,
John Cullinan <cullinan@bard.edu>,
Aditya Khurmi <akhurmi@umass.edu>,
Jeffrey Hatley <hatleyj@union.edu>,
Margaret Robinson <robinson@mtholyoke.edu>,
Tori Day <day22v@mtholyoke.edu>,
Geremias Polanco <gpolanco@smith.edu>,
Jennifer Beineke <jbeineke@wne.edu>,
Caleb Shor <cshor@wne.edu>,
Brody Lynch <bjlynch@umass.edu>,
Benjamin Levine <belevine@umass.edu>,
Seong Eun Jung <seongeunjung@umass.edu>,
Zichao Lin <zichaolin@umass.edu>,
Arindam Bhattacharyya <arindambhatt@umass.edu>,
Anika O'Donnell <odonnell@umass.edu>,
Burak Cakir <bcakir@umass.edu>,
Sharon Spaulding <sspaulding@umass.edu>,
Owen Gwilliam <ogwilliam@umass.edu>,
Yujeong Han <yujeonghan@umass.edu>,
Rusiru Gambheera <rusiru@ucsb.edu>,
Andrey Brinsko <abrinsko@umass.edu>,
<mzheng27@amherst.edu>
